#!/bin/sh

# Update the generated documentation
echo "Updating generated docs"
python3 docs/src/create_metrics_and_sources_md.py

# Add the updated documentation to staging
echo "Adding generated docs"
git add docs/METRICS_AND_SOURCES.md

FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.py" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs python3 -m black

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
