"""Metric and parameter units."""

from .base import StrEnum


class Unit(StrEnum):
    """Supported units."""

    BLOCK = "block"
    BLOCKS = "blocks"
    BRANCH = "branch"
    BRANCHES = "branches"
    CI_JOB = "CI-job"
    CI_JOBS = "CI-jobs"
    CI_JOB_RUN = "CI-job run"
    CI_JOB_RUNS = "CI-job runs"
    COMPLEX_UNIT = "complex unit"
    COMPLEX_UNITS = "complex units"
    COMPLIANCE = "compliance"
    DAY = "day"
    DAYS = "days"
    DEPENDENCY = "dependency"
    DEPENDENCIES = "dependencies"
    DOWNVOTE = "downvote"
    DOWNVOTES = "downvotes"
    FAILED_DEPLOYMENT = "failed deployment"
    FAILED_DEPLOYMENTS = "failed deployments"
    ISSUE = "issue"
    ISSUES = "issues"
    LINE = "line"
    LINES = "lines"
    LONG_UNIT = "long unit"
    LONG_UNITS = "long units"
    MANUAL_TEST_CASE = "manual test case"
    MANUAL_TEST_CASES = "manual test cases"
    MERGE_REQUEST = "merge request"
    MERGE_REQUESTS = "merge requests"
    METRIC = "metric"
    METRICS = "metrics"
    MINUTE = "minute"
    MINUTES = "minutes"
    MISSING_METRIC = "missing metric"
    MISSING_METRICS = "missing metrics"
    NONE = ""
    SECURITY_WARNING = "security warning"
    SECURITY_WARNINGS = "security warnings"
    SPRINT = "sprint"
    SPRINTS = "sprints"
    SUPPRESSED_VIOLATION = "suppressed violation"
    SUPPRESSED_VIOLATIONS = "suppressed violations"
    TEST_CASE = "test case"
    TEST_CASES = "test cases"
    TEST_SUITE = "test suite"
    TEST_SUITES = "test suites"
    TEST = "test"
    TESTS = "tests"
    TODO_OR_FIXME_COMMENT = "todo or fixme comment"
    TODO_AND_FIXME_COMMENTS = "todo and fixme comments"
    TRANSACTION = "transaction"
    TRANSACTIONS = "transactions"
    UNCOVERED_BRANCH = "uncovered branch"
    UNCOVERED_BRANCHES = "uncovered branches"
    UNCOVERED_LINE = "uncovered line"
    UNCOVERED_LINES = "uncovered lines"
    UNIT_WITH_TOO_MANY_PARAMETERS = "unit with too many parameters"
    UNITS_WITH_TOO_MANY_PARAMETERS = "units with too many parameters"
    UPVOTE = "upvote"
    UPVOTES = "upvotes"
    USER_STORY_POINT = "user story point"
    USER_STORY_POINTS = "user story points"
    USER_STORY_POINT_PER_SPRINT = "user story point per sprint"
    USER_STORY_POINTS_PER_SPRINT = "user story points per sprint"
    VIOLATION = "violation"
    VIOLATIONS = "violations"
    VIRTUAL_USER = "virtual user"
    VIRTUAL_USERS = "virtual users"
