text  # unused variable (src/model/issue_tracker.py:26)
api  # unused variable (src/routes/plugins/auth_plugin.py:26)
_.apply  # unused method (src/routes/plugins/auth_plugin.py:31)
api  # unused variable (src/routes/plugins/injection_plugin.py:19)
_.setup  # unused method (src/routes/plugins/injection_plugin.py:26)
_.apply  # unused method (src/routes/plugins/injection_plugin.py:33)
_.content_type  # unused attribute (src/routes/report.py:122)
_.content_type  # unused attribute (src/routes/report.py:140)
