apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.database.claimName }}
  name: {{ .Values.database.claimName }}
spec:
  accessModes:
    - {{ .Values.database.accessMode }}
  resources:
    requests:
      storage: {{ .Values.database.storageSize }}
  storageClassName: {{ .Values.database.storageClassName }}
