apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.api_server.name }}
  name: {{ .Values.api_server.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.api_server.name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.api_server.name }}
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: mongodb://root:root@{{ .Values.database.name }}:27017
            - name: API_SERVER_PORT
              value: "5001"
            - name: FORWARD_AUTH_ENABLED
              value: "False"
            - name: FORWARD_AUTH_HEADER
              value: X-Forwarded-User
            - name: LDAP_LOOKUP_USER_DN
              value: {{ .Values.ldap.lookupUserDN }}
            - name: LDAP_LOOKUP_USER_PASSWORD
              value: {{ .Values.ldap.lookupUserPassword }}
            - name: LDAP_ROOT_DN
              value: {{ .Values.ldap.rootDN }}
            - name: LDAP_SEARCH_FILTER
              value: {{ .Values.ldap.search }}
            - name: LDAP_URL
              value: {{ .Values.ldap.url }}
            - name: LOAD_EXAMPLE_REPORTS
              value: "True"
          image: {{ .Values.api_server.image }}
          imagePullPolicy: Always
          name: {{ .Values.api_server.name }}
          resources: {}
          securityContext:
            capabilities:
              drop:
                - ALL
      restartPolicy: Always
      imagePullSecrets:
        - name: quality-time-pullsecret
