apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.notifier.name }}
  name: {{ .Values.notifier.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.notifier.name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.notifier.name }}
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: mongodb://root:root@{{ .Values.database.name }}:27017
            - name: NOTIFIER_SLEEP_DURATION
              value: "60"
          image: {{ .Values.notifier.image }}
          imagePullPolicy: Always
          name: {{ .Values.notifier.name }}
          resources: {}
          securityContext:
            capabilities:
              drop:
                - ALL
      restartPolicy: Always
      imagePullSecrets:
        - name: quality-time-pullsecret
