apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.renderer.name }}
  name: {{ .Values.renderer.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.renderer.name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.renderer.name }}
    spec:
      containers:
        - env:
            - name: LC_ALL
              value: en_GB.UTF-8
            - name: PROXY_HOST
              value: {{ .Values.www.name }}
            - name: PROXY_PORT
              value: "80"
            - name: PROXY_PROTOCOL
              value: "http"
            - name: TZ
              value: Europe/Amsterdam
          image: {{ .Values.renderer.image }}
          imagePullPolicy: Always
          name: {{ .Values.renderer.name }}
          resources: {}
      restartPolicy: Always
      imagePullSecrets: 
        - name: quality-time-pullsecret
