apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.www.name }}
  name: {{ .Values.www.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.www.name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.www.name }}
    spec:
      containers:
        - env:
            - name: EXTERNAL_SERVER_HOST
              value: {{ .Values.external_server.name }}
            - name: EXTERNAL_SERVER_PORT
              value: "5001"
            - name: FRONTEND_HOST
              value: {{ .Values.frontend.name }}
            - name: FRONTEND_PORT
              value: "5000"
          image: {{ .Values.www.image }}
          imagePullPolicy: Always
          name: {{ .Values.www.name }}
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
      imagePullSecrets: 
        - name: quality-time-pullsecret
