disable-auto-file-load:
  - python

additional-dependency-files:
  - type: pip-requirements-txt
    path: components/collector/requirements.in
  - type: pip-requirements-txt
    path: components/collector/requirements-dev.in

  - type: pip-requirements-txt
    path: components/notifier/requirements.in
  - type: pip-requirements-txt
    path: components/notifier/requirements-dev.in

  - type: pip-requirements-txt
    path: components/external_server/requirements.in
  - type: pip-requirements-txt
    path: components/external_server/requirements-dev.in

  - type: pip-requirements-txt
    path: components/shared_python/requirements.in
  - type: pip-requirements-txt
    path: components/shared_python/requirements-dev.in

  - type: pip-requirements-txt
    path: tests/application_tests/requirements-dev.in
  - type: pip-requirements-txt
    path: tests/application_tests/requirements.txt
  - type: pip-requirements-txt
    path: tests/feature_tests/requirements-dev.in

  - type: pip-requirements-txt
    path: release/requirements-dev.in

  - type: pip-requirements-txt
    path: docs/requirements-dev.in
  - type: npm-package-json
    path: docs/package.json

  - type: npm-package-json
    path: components/frontend/package.json

additional-deps:
  python:
    - name: bandit
      repo: PyCQA/bandit
    - name: bottle
      repo: bottlepy/bottle
    - name: furo
      repo: pradyunsg/furo
    - name: mypy
      repo: python/mypy
    - name: selenium
      repo: SeleniumHQ/selenium
    - name: typing_extensions
      repo: python/typing

ignore-failures:
  python:
    - behave
  javascript:
    - semantic-ui-css
