version = 1

test_patterns = [
  "**/tests/**",
  "test_*.py"
]

exclude_patterns = [
  "**/.vulture_ignore_list.py"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "requirements-dev.txt",
  "components/collector/requirements.txt",
  "components/collector/requirements-dev.txt",
  "components/server/requirements.txt",
  "components/server/requirements-dev.txt",
]
additional_builtins = ["given", "when", "then"]

  [analyzers.meta]
  runtime_version = "3.x.x"
  type_checker = "mypy"
  max_line_length = 120

