version = 1

test_patterns = [
  "**/tests/**",
  "test_*.py"
]

exclude_patterns = [
  "**/.vulture_ignore_list.py"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "release/requirements-dev.txt",
  "tests/application_tests/requirements-dev.txt",
  "tests/feature_tests/requirements-dev.txt",
  "components/collector/requirements.txt",
  "components/collector/requirements-dev.txt",
  "components/notifier/requirements.txt",
  "components/notifier/requirements-dev.txt",
  "components/server/requirements.txt",
  "components/server/requirements-dev.txt",
  "components/shared_python/requirements.txt",
  "components/shared_python/requirements-dev.txt",
]
additional_builtins = ["given", "when", "then"]

  [analyzers.meta]
  runtime_version = "3.x.x"
  type_checker = "mypy"
  max_line_length = 120

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "components/collector/Dockerfile",
    "components/database/Dockerfile",
    "components/frontend/Dockerfile",
    "components/ldap/Dockerfile",
    "components/notifier/Dockerfile",
    "components/proxy/Dockerfile",
    "components/renderer/Dockerfile",
    "components/server/Dockerfile",
    "components/testdata/Dockerfile",
  ]

[[analyzers]]
name = "secrets"
enabled = true
