image: cimg/python:3.9.6-node

stages:
  - test

collector:
  stage: test
  script:
    - cd components/collector
    - pip install -r requirements.txt -r requirements-dev.txt
    - ci/unittest.sh
    - ci/quality.sh
  coverage: '/ \d+%/'
  artifacts:
    paths:
      - components/collector/build/unittest-coverage

notifier:
  stage: test
  script:
    - cd components/notifier
    - pip install -r requirements.txt -r requirements-dev.txt
    - ci/unittest.sh
    - ci/quality.sh
  coverage: '/ \d+%/'
  artifacts:
    paths:
      - components/notifier/build/unittest-coverage

server:
  stage: test
  script:
    - cd components/server
    - pip install -r requirements.txt -r requirements-dev.txt
    - ci/unittest.sh
    - ci/quality.sh
  coverage: '/ \d+%/'
  artifacts:
    paths:
      - components/server/build/unittest-coverage

docs:
  stage: test
  script:
    - cd docs
    - pip install -r requirements-dev.txt
    - npm install
    - ci/unittest.sh
    - ci/quality.sh
  coverage: '/ \d+%/'
  artifacts:
    paths:
      - docs/build/unittest-coverage
