# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  apt_packages:
    - graphviz
  jobs:
    pre_create_environment:
      - pip install uv==0.9.7
    install:
      - cd docs && VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH ci/install-dependencies.sh

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/src/conf.py

# Additional formats to build
formats:
  - pdf
