"""Robot Framework source."""

from ..meta.entity import Color
from ..meta.source import Source
from ..parameters import access_parameters, TestResult

from .jenkins import jenkins_access_parameters


ALL_ROBOT_FRAMEWORK_METRICS = ["source_up_to_dateness", "source_version", "tests"]

ROBOT_FRAMEWORK = Source(
    name="Robot Framework",
    description="Robot Framework is a generic open source automation framework for acceptance testing, acceptance "
    "test driven development, and robotic process automation.",
    url="https://robotframework.org",
    parameters=dict(
        test_result=TestResult(values=["fail", "pass", "skip"]),
        **access_parameters(ALL_ROBOT_FRAMEWORK_METRICS, source_type="Robot Framework report", source_type_format="XML")
    ),
    entities=dict(
        tests=dict(
            name="test",
            attributes=[
                dict(name="Test name", key="name"),
                dict(name="Test result", color={"fail": Color.NEGATIVE, "pass": Color.POSITIVE}),
            ],
        )
    ),
)

ALL_ROBOT_FRAMEWORK_JENKINS_PLUGIN_METRICS = ["source_up_to_dateness", "tests"]

ROBOT_FRAMEWORK_JENKINS_PLUGIN = Source(
    name="Robot Framework Jenkins plugin",
    description="A Jenkins plugin for Robot Framework, a generic open source automation framework for acceptance "
    "testing, acceptance test driven development, and robotic process automation.",
    url="https://plugins.jenkins.io/robot/",
    parameters=dict(
        test_result=TestResult(values=["fail", "pass"], api_values={"fail": "overallFailed", "pass": "overallPassed"}),
        **jenkins_access_parameters(
            ALL_ROBOT_FRAMEWORK_JENKINS_PLUGIN_METRICS,
            kwargs=dict(
                url=dict(
                    help="URL to a Jenkins job with a test report generated by the Robot Framework plugin. "
                    "For example, 'https://jenkins.example.org/job/robot' or "
                    "https://jenkins.example.org/job/robot/job/master' in case of a pipeline job."
                )
            ),
        )
    ),
)
