_.subject_uuids  # unused attribute (src/shared/model/report.py:37)
api  # unused variable (src/shared/routes/plugins/injection_plugin.py:12)
_.setup  # unused method (src/shared/routes/plugins/injection_plugin.py:19)
_.apply  # unused method (src/shared/routes/plugins/injection_plugin.py:25)
NotificationDestinationId  # unused variable (src/shared/utils/type.py:15)
