---
# Extra services and overridden parameters for testing in a CI-environment.
# Mongo-express is not started.

x-security-opt: &security-opt
  - no-new-privileges:true

services:
  www:
    build: ../components/proxy
  frontend:
    build: ../components/frontend
  collector:
    build:
      context: ..
      dockerfile: components/collector/Dockerfile
  notifier:
    build:
      context: ..
      dockerfile: components/notifier/Dockerfile
  api_server:
    build:
      context: ..
      dockerfile: components/api_server/Dockerfile
    environment:
      - LOAD_EXAMPLE_REPORTS=False
    depends_on:
      - ldap
  database:
    build: ../components/database
    ports:
      - "127.0.0.1:27017:27017"
  ldap:
    build: ../components/testldap
    ports:
      - "127.0.0.1:389:389"
    security_opt: *security-opt
  renderer:
    build: ../components/renderer
    ports:
      - "127.0.0.1:9000:9000"
  selenium:
    image: selenium/standalone-firefox:149.0.2
    shm_size: 2gb
    ports:
      - "127.0.0.1:4444:4444"
    security_opt: *security-opt
