---
# Extra services and overridden parameters for testing in a CI-environment.
# Mongo-express is not started.

x-security-opt: &security-opt
  - no-new-privileges:true

services:
  www:
    build: ../components/proxy
  frontend:
    build: ../components/frontend
  collector:
    build:
      context: ..
      dockerfile: components/python.Dockerfile
      args:
        COMPONENT: collector
  notifier:
    build:
      context: ..
      dockerfile: components/python.Dockerfile
      args:
        COMPONENT: notifier
  api_server:
    build:
      context: ..
      dockerfile: components/python.Dockerfile
      args:
        COMPONENT: api_server
    environment:
      - LOAD_EXAMPLE_REPORTS=False
    depends_on:
      - ldap
  database:
    build: ../components/database
    ports:
      - "127.0.0.1:27017:27017"
  ldap:
    build: ../components/testldap
    image: ictu/quality-time_testldap:${QUALITY_TIME_VERSION}
    ports:
      - "127.0.0.1:10389:389"
    security_opt: *security-opt
  renderer:
    build: ../components/renderer
    ports:
      - "127.0.0.1:9000:9000"
  selenium:
    image: selenium/standalone-firefox:152.0.2-20260606@sha256:2f586a23f0f74f43c806de53e49b99676dbb9cb34f9a1d40347d4f2b95928b7a # yamllint disable-line rule:line-length
    shm_size: 2gb
    ports:
      - "127.0.0.1:4444:4444"
    cap_drop:
      - ALL
    security_opt: *security-opt
