FROM osixia/openldap:1.4.0

LABEL maintainer="Frank Niessink <frank.niessink@ictu.nl>"
LABEL description="Quality-time test LDAP server"

COPY bootstrap /container/service/slapd/assets/config/bootstrap
