FROM osixia/openldap:1.5.0

LABEL maintainer="Quality-time team <Quality-time@ictu.nl>"
LABEL description="Quality-time test LDAP server"

COPY bootstrap /container/service/slapd/assets/config/bootstrap
