__new__  # unused function (src/source_collectors/azure_devops/source_up_to_dateness.py:60)
__new__  # unused function (src/source_collectors/gitlab/source_up_to_dateness.py:136)
scan_status  # unused variable (src/source_collectors/harbor/security_warnings.py:43)
id  # unused variable (src/source_collectors/jira/velocity.py:17)
id  # unused variable (src/source_collectors/jira/velocity.py:31)
