"""Base class for unit tests for the Axe report generated by axe-selenium-python."""

from ..source_collector_test_case import SourceCollectorTestCase


class AxeSeleniumPythonTestCase(SourceCollectorTestCase):  # skipcq: PTC-W0046
    """Base class for testing axe-selenium-python collectors."""

    SOURCE_TYPE = "axe_selenium_python"
