---
apiVersion: v1
kind: Secret
metadata:
  name: quality-time-db-secret
  labels:
    app.kubernetes.io/name: quality-time
    app.kubernetes.io/instance: quality-time
data:
  DATABASE_USERNAME: ""
  DATABASE_PASSWORD: ""
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: quality-time-ldap-secret
  labels:
    app.kubernetes.io/name: quality-time
    app.kubernetes.io/instance: quality-time
data:
  LDAP_LOOKUP_USER_PASSWORD: ""
type: Opaque
