name: Application tests

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run application tests
        env:
          QUALITY_TIME_VERSION: v4.2.0
          ENV: ci
          COMPOSE_PATH_SEPARATOR: ':'
          COMPOSE_FILE: docker/docker-compose.yml:docker/docker-compose.ci.yml
        run: |
          mkdir -p build
          echo "Echoing environment vars"
          echo $COMPOSE_PATH_SEPARATOR
          echo $COMPOSE_FILE
          echo $CI
          echo "/Echoing environment vars"
          docker compose build && docker compose up -d
          docker run -t -w `pwd` -v `pwd`:`pwd` --network=quality-time_default python:3.10.5-bullseye tests/application_tests/ci/test.sh
      - name: Save container logs
        if: always()
        run: |
          docker compose logs > build/containers.log
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: build-artifacts
          path: build
