name: Application tests

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      QUALITY_TIME_VERSION: v3.37.0-rc.4
      ENV: ci
      COMPOSE_PATH_SEPARATOR: ":"
      COMPOSE_FILE: docker/docker-compose.yml:docker/docker-compose.ci.yml

    steps:
      - uses: actions/checkout@v3
      - name: Run application tests
        run: |
          mkdir -p build
          docker compose build && docker compose up -d
          docker run -t -w `pwd` -v `pwd`:`pwd` --network=container:quality-time-www-1 python:3.10.4-bullseye tests/application_tests/ci/test.sh
      - name: Save container logs
        if: always()
        run: |
          docker compose logs > build/containers.log
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: build-artifacts
          path: build
