name: Create Cluster

on: pull_request

jobs:
  create-cluster:
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    runs-on: ubuntu-latest
    steps:
      - name: MicroShift OpenShift Cluster
        uses: container-tools/microshift-action@v0.3.0
