name: Application tests

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run application tests
        env:
          QUALITY_TIME_VERSION: v4.3.0
          ENV: ci
        run: |
          mkdir -p build
          docker compose --file docker/docker-compose.yml --file docker/docker-compose.ci.yml --project-name quality-time up --build --detach --wait
          docker run -t -w `pwd` -v `pwd`:`pwd` --network=container:quality-time-www-1 python:3.10.6-bullseye tests/application_tests/ci/test.sh
      - name: Save container logs
        if: always()
        run: |
          docker compose logs > build/containers.log
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: build-artifacts
          path: build
