name: Database

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Quality
      run: |
        cd components/database
        ci/quality.sh
