name: Server

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: '3.9.5'
    - name: Install dependencies
      run: |
        cd docs
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Test
      run: |
        cd docs
        ci/unittest.sh
    - name: Quality
      run: |
        cd components/server
        ci/quality.sh
