---
name: Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.29"
      - name: Install dependencies, run unit tests and check quality
        run: |
          cd docs
          uv venv
          ci/pip-install.sh
          npm install --ignore-scripts
          ci/unittest.sh
          ci/quality.sh
