---
name: Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.7.20"
      - name: Install dependencies, run unit tests and check quality
        run: |
          cd docs
          ci/install-dependencies.sh
          ci/unittest.sh
          ci/quality.sh
