name: Documentation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2.3.2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd docs
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        npm install
    - name: Test
      run: |
        cd docs
        ci/unittest.sh
    - name: Quality
      run: |
        cd docs
        ci/quality.sh
