name: Documentation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd docs
        ci/pip-install.sh
    - name: Test
      run: |
        cd docs
        ci/unittest.sh
    - name: Quality
      run: |
        cd docs
        ci/quality.sh
