name: Documentation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        cd docs
        ci/pip-install.sh
        npm install --ignore-scripts
    - name: Test
      run: |
        cd docs
        ci/unittest.sh
    - name: Quality
      run: |
        cd docs
        ci/quality.sh
