---
name: Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.22"
      - name: Install dependencies, run unit tests and check quality
        run: |
          cd docs
          uv venv
          ci/pip-install.sh
          corepack enable yarn
          yarn
          ci/unittest.sh
          ci/quality.sh
