---
name: Hadolint

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {}
    strategy:
      matrix:
        include:
          - docker_file: components/python.Dockerfile
          - docker_file: components/database/Dockerfile
          - docker_file: components/frontend/Dockerfile
          - docker_file: components/proxy/Dockerfile
          - docker_file: components/renderer/Dockerfile
          - docker_file: components/testdata/Dockerfile

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Hadolint ${{ matrix.docker_file }}
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: ${{ matrix.docker_file }}
