---
name: Documentation linkcheck

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
          version-file: tools/third_party/pyproject.toml
      - name: Run sphinx linkcheck
        run: uv tool run --directory docs --from $(uv export --project tools/third_party --only-group just --quiet --no-hashes --no-header) just linkcheck # yamllint disable-line rule:line-length
