---
name: Documentation linkcheck

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true
          version-file: tools/third_party/pyproject.toml
      - name: Run sphinx linkcheck
        run: uv tool run --directory docs --from $(uv export --project tools/third_party --only-group just --quiet --no-hashes --no-header) just linkcheck # yamllint disable-line rule:line-length
