name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.0'
    - name: Install prerequisites
      run: |
        sudo apt-get install libxml2-dev libxslt-dev python-dev
        python -m pip install --upgrade pip
        python -m pip install wheel
    - name: Collector
      run: |
        cd components/collector
        pip install -r requirements.txt -r requirements-dev.txt
        pylint src tests
    - name: Server
      run: |
        cd components/server
        pip install -r requirements.txt -r requirements-dev.txt
        pylint src tests
    - name: Notifier
      run: |
        cd components/notifier
        pip install -r requirements.txt -r requirements-dev.txt
        pylint src tests
