---
name: Release script quality

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2
      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
          version-file: tools/third_party/pyproject.toml
      - name: Install dependencies and check quality
        run: uv tool run --directory tools/release --from $(uv export --project
          tools/third_party --only-group just --quiet --no-hashes --no-header)
          just ci
